version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - spark-network

  fetcher:
    build:
      context: ./fetcher
      dockerfile: Dockerfile
    container_name: fetcher
    depends_on:
      - mongodb
    environment:
      - API_KEY=66343612d0556eebd2618dd39051ab66
      - LAT=59.9375
      - LON=30.308611
    restart: always
    networks:
      - spark-network
      
  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark
    networks:
      - spark-network

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=password
    volumes:
      - ./jupyter:/home/jovyan/work
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    networks:
      - spark-network

volumes:
  mongodb_data:
  jupyter_data:

networks:
  spark-network:
    driver: bridge